"""Create Origin and Tool models

Revision ID: d11cbc97bd2b
Revises: 
Create Date: 2021-02-02 21:48:03.926544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d11cbc97bd2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "origins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("coordinates", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tool_number", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("z_offset", sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column("diameter", sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("tool_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tools")
    op.drop_table("origins")
    # ### end Alembic commands ###
